server {
    listen 80;
    server_name sovanisova.ru www.sovanisova.ru sovanisova.kalmykov-dev.ru;

    # проверка домена для продления сертификата должна оставаться на http
    location ^~ /.well-known/acme-challenge/ { root /var/www/acme; default_type text/plain; }

    location / { return 301 https://sovanisova.ru$request_uri; }
}
